[package]
name = "gol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
ggez = "0.8.1"
dashmap = { version = "5.4.0", features = ["rayon"] }
rayon = { version = "1.6.1"}